### ISSUE TITLE
hello，大佬你好，我大概看了一下你的几个工程，想问一下可以将你的yolov5第二版中的prune_finetune.py直接用到这里接着稀疏训练之后吗

### ISSUE THREAD

**Issue by YiJun-Yang** [ZJU-lishuang/yolov5-v3#1]

**Comment by YiJun-Yang** [comment]
如题，想问一下现在这个版本有可以用的剪枝训练吗

**Comment by ZJU-lishuang** [comment]
Now I am wroking on prune tutorials in yolov5_v3 .
If you want to use prune_finetune.py in yolov5_v3,I think there are some bugs need to be fixed.

**Comment by YiJun-Yang** [comment]
prune_finetune.py in yolov5_v2？

**Comment by ZJU-lishuang** [comment]
prune_finetune.py is in [yolov5](https://github.com/ZJU-lishuang/yolov5/blob/master/prune_finetune.py).
Some layers are not supported in yolov5_v3 now.I haven't test it.

**Comment by YiJun-Yang** [comment]
I am trying to transformer it to which yolov5_v3 supports according to train_sparsity.py and prune_finetune.py. but now confusing about model here, such as imgsize should be 416 or opt.img_size[0]?


    # Create model
    # model = Model(opt.cfg, nc=nc).to(device)
    model = Darknet(opt.cfg, (opt.img_size[0], opt.img_size[0])).to(device)
    initialize_weights(model)
    # cfg_model = Darknet('cfg/yolov5s.cfg', (416, 416)).to(device)

**Comment by yangyijun0924** [comment]
![图片](https://user-images.githubusercontent.com/45503894/102466714-5c1cfc00-408a-11eb-891b-c74c458a5079.png)

**Comment by YiJun-Yang** [comment]
![图片](https://user-images.githubusercontent.com/45503894/102466909-99818980-408a-11eb-90dd-ea6138ac7184.png)

**Comment by YiJun-Yang** [comment]
请问你输入的这些cfg文件都是哪里来的呀，比如prune_0.8_keep_0.01_8x_yolov5s_hand.cfg

**Comment by ZJU-lishuang** [comment]
cfg有两种
1、模型剪枝自动生成的。
2、根据原始yaml手动转换对应的cfg
prune_0.8_keep_0.01_8x_yolov5s_hand.cfg这个是自动生成的

**Comment by ZJU-lishuang** [comment]
@yangyijun0924 now the prune_finetune.py file for yolov5_v3 has been updated.

**Comment by YiJun-Yang** [comment]
非常感谢，那么做这个微调训练大概都是训练多少代呢

**Comment by ZJU-lishuang** [comment]
just treat it as normal training
